@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> Main: initialize()
Main -> Path: <<create>> (userPath)
Path -> Main: (Path : p)
Main -> MazeExplorer: <<create>> (userMaze)

MazeExplorer -> Maze: <<create>> (userMaze)
Maze -> MazeExplorer: (Maze: maze)


alt userPath not null



MazeExplorer -> VerifyPath: verify(Path : p)
VerifyPath -> MazeExplorer: boolean
MazeExplorer -> Main: boolean

else baseline not null
MazeExplorer -> MazeExplorer: compare(String: baseline, method)
MazeExplorer -> RightHand: <<create>>
RightHand -> MazeExplorer: RightHand: baseline
MazeExplorer -> GraphSolution: <<create>>
GraphSolution -> MazeExplorer: GraphSolution: method
MazeExplorer -> Baseline: <<create>> (baseline)
Baseline -> MazeExplorer: Baseline: base
Baseline -> Baseline: speedUp(method)
Baseline -> MazeExplorer
MazeExplorer -> Main

else solve maze

MazeExplorer -> GraphSolution: solve(String: method)
GraphSolution -> Player : <<create>>
Player -> GraphSolution : Player : player
GraphSolution -> GraphBuilder: <<create>>

GraphBuilder -> Graph: <<create>>
Graph -> GraphBuilder: Graph: graph
GraphBuilder -> GraphBuilder: build()

GraphBuilder -> GraphSolution: graph



GraphSolution -> MazeExplorer: (Path : solution)
MazeExplorer -> Main: solution


end


@enduml
